modLoader="kotlinforforge"
loaderVersion="[1,)"

license="BSD 2-Clause"
issueTrackerURL="https://github.com/thecodewarrior/Hooked/issues"

[[mods]]
modId="hooked"
version="${file.jarVersion}"
displayName="Hooked"
logoFile="hooked_banner.png"
credits="Much thanks to QuickHull3d"
authors="thecodewarrior"
description='''
Hooked: Grappling hooks done simple, natural, and useful.
'''

[[dependencies.hooked]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.hooked]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"
[[dependencies.hooked]]
    modId="librarianlib"
    mandatory=true
    versionRange="[5.0.0a3,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.hooked]]
    modId="curios"
    mandatory=true
    versionRange="[FORGE-1.15.2-2.0.2.6,)"
    ordering="NONE"
    side="BOTH"